### PR TITLE
project: remove bindgen

### PR DESCRIPTION
**Pull request by xobs**
bindgen makes it very difficult to cross-compile this program, because it makes lots of assumptions about the build environment.

Remove the `bindgen` definitions and ship direct versions of the structs.

This enables cross-compiling the project from other platforms.

### CODE REVIEW

**Comment by xobs** [comment]
I recognize this likely won't work due to the fact that the ws281x library underneath uses unsized ints. However, there really are only two target architectures: 32- and 64-bits. So a better alternative may be to simply add guard checks to use `u32` or `u64` in place of `i32`.

Alternately, `isize` would work.

Either way, with this patch in place I'm able to cross-compile from a Mac.

**Comment by JMurph2015** [comment]
I would rather not remove bindgen as it breaks our ability to update with the underlying library (without having to manually do so).  Bindgen should work on Mac so long as you have host-native Clang and Rustc installed, since bindgen doesn't need to do machine code generation.

**Comment by xobs** [comment]
I know that it doesn't build under Windows without a lot of custom packages, and it also doesn't build under Mac:

```
rpi-ws281x-rust (b0cf53b) is 📦 v0.4.4 via 🦀 v1.73.0 
❯ cargo build --target arm-unknown-linux-musleabihf --example basic                                                                                                 (base) 
    Updating crates.io index
   Compiling proc-macro2 v1.0.69
   Compiling unicode-ident v1.0.12
   Compiling libc v0.2.149
   Compiling glob v0.3.1
   Compiling regex-syntax v0.8.2
   Compiling memchr v2.6.4
   Compiling minimal-lexical v0.2.1
   Compiling bindgen v0.60.1
   Compiling lazycell v1.3.0
   Compiling lazy_static v1.4.0
   Compiling bitflags v1.3.2
   Compiling shlex v1.2.0
   Compiling nom v7.1.3
   Compiling peeking_take_while v0.1.2
   Compiling rustc-hash v1.1.0
   Compiling serde v1.0.189
   Compiling clang-sys v1.6.1
   Compiling regex-automata v0.4.3
   Compiling cexpr v0.6.0
   Compiling quote v1.0.33
   Compiling syn v2.0.38
   Compiling cc v1.0.83
   Compiling regex v1.10.2
   Compiling serde_derive v1.0.189
   Compiling rs_ws281x v0.4.4 (/Users/sean/Code/Stuff/jig/rpi-ws281x-rust)
error: failed to run custom build command for `rs_ws281x v0.4.4 (/Users/sean/Code/Stuff/jig/rpi-ws281x-rust)`

Caused by:
  process didn't exit successfully: `/Users/sean/Code/Stuff/jig/rpi-ws281x-rust/target/debug/build/rs_ws281x-31be7751b83a35a1/build-script-build` (signal: 6, SIGABRT: process abort signal)
  --- stderr
  dyld[63533]: Library not loaded: @rpath/libclang.dylib
    Referenced from: <F7A3F574-58C3-35DA-A957-4BD24883C066> /Users/sean/Code/Stuff/jig/rpi-ws281x-rust/target/debug/build/rs_ws281x-31be7751b83a35a1/build-script-build
    Reason: tried: '/Users/sean/Code/Stuff/jig/rpi-ws281x-rust/target/debug/deps/libclang.dylib' (no such file), '/Users/sean/Code/Stuff/jig/rpi-ws281x-rust/target/debug/libclang.dylib' (no such file), '/Users/sean/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libclang.dylib' (no such file), '/Users/sean/.rustup/toolchains/stable-aarch64-apple-darwin/lib/libclang.dylib' (no such file), '/Users/sean/lib/libclang.dylib' (no such file), '/usr/local/lib/libclang.dylib' (no such file), '/usr/lib/libclang.dylib' (no such file, not in dyld cache)


rpi-ws281x-rust (b0cf53b) is 📦 v0.4.4 via 🦀 v1.73.0 took 6s 
❯ clang --version                                                                                                                                   (base) 
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

rpi-ws281x-rust (b0cf53b) is 📦 v0.4.4 via 🦀 v1.73.0 
❯                                                                                                                                                   (base) 
```

I think bindgen works generally okay if you're not cross-compiling and/or are on Linux. By removing bindgen as a dependency it allows for more platforms. For example, on Windows I can build it by adding `arm-linux-musleabihf-gcc` to my PATH.

However, I do recognize that perhaps this is an approach that this project may not wish to take because it requires manually following the releases. If that's the case, please close this PR.

**Comment by JMurph2015** [comment]
From Bindgen's Requirements page:
> [macOS](https://rust-lang.github.io/rust-bindgen/requirements.html#macos)
> 
> If you use Homebrew:
> 
> $ brew install llvm

Of all the complications to cross-compiling here (for instance, I really wish the Raspberry Pi would work with the standard Rust cross compile toolchain, but it doesn't), this is by far the easiest to live with.

**Pull request closed without merging**
